#!/bin/bash
#
# Install a full puppet
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
DEST_DIR="/opt/puppet"
CONFIG_DIR="/etc/puppet"
VAR_DIR="/var/lib/puppet"
LOG_DIR="/var/log/puppet"
PREFIX="/usr"
USAGE="usage: $0"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# Move the actual files into place
rm -rf $DEST_DIR/* || error_exit "Cannot remove contents of $DEST_DIR"
mkdir -p $DEST_DIR || error_exit "Cannot create $DEST_DIR"
cp -R $INSTALLER_DIR $DEST_DIR || error_exit "Cannot install to $DEST_DIR"
rm -f $DEST_DIR/$PROGNAME
rm -rf $DEST_DIR/embedded/etc/puppet

# Move config files to /etc
mkdir -p $CONFIG_DIR
if [ ! -e /etc/puppet/puppet.conf ] ; then
  cp -R $INSTALLER_DIR/embedded/etc/puppet $CONFIG_DIR
fi
if [ ! -e /etc/default/puppet ] ; then
  cp $INSTALLER_DIR/embedded/etc/default/puppet $CONFIG_DIR/puppet
fi


exit 0
