#!/bin/bash
#
# Perform necessary puppet setup steps
# after package is installed.
#

PROGNAME=$(basename $0)
INSTALLER_DIR="/opt/puppet"
CONFIG_DIR="/etc/puppet"
VAR_DIR="/var/lib/puppet"
LOG_DIR="/var/log/puppet"
PREFIX="/usr"
PUPPET_GEM_DIR=`ls -dr ${INSTALLER_DIR}/embedded/lib/ruby/gems/*/gems/puppet-* | head -1`

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

#Link binaries
ln -sf $INSTALLER_DIR/bin/puppet $PREFIX/bin || error_exit "Cannot link puppet to $PREFIX/bin"
ln -sf $INSTALLER_DIR/bin/facter $PREFIX/bin || error_exit "Cannot link facter to $PREFIX/bin"

# Create the "puppet" user
if ! getent passwd puppet > /dev/null; then
  adduser --quiet --system --group --home $VAR_DIR  \
    --no-create-home                                 \
    --gecos "Puppet configuration management daemon" \
    puppet
fi

# Set correct permissions and ownership for puppet directories
if [ ! -d "$VAR_DIR" ]; then
  mkdir -m 750 $VAR_DIR
  chown puppet:puppet $VAR_DIR
fi

if [ ! -d "$VAR_DIR/state" ]; then
  mkdir -m 755 $VAR_DIR/state
  chown puppet:puppet $VAR_DIR
fi

if [ ! -d "$LOG_DIR" ]; then
  mkdir -m 750 $LOG_DIR
  chown puppet:puppet $LOG_DIR
fi

# Create config if it doesn't exist
if [ ! -d "$CONFIG_DIR" ]; then
  mkdir -m 755 $CONFIG_DIR
fi

# Copy in default configuration if none exists already (FIXME: support OS's other than Debian)
if [ ! -e "$CONFIG_DIR"/puppet.conf ]; then
  cp ${PUPPET_GEM_DIR}/ext/debian/puppet.conf ${CONFIG_DIR}/puppet.conf
  chmod 644 ${CONFIG_DIR}/puppet.conf
fi

# Copy in init scripts if none exists already (FIXME: support OS's other than Debian)
if [ ! -e /etc/init.d/puppet ] ; then
  cp ${PUPPET_GEM_DIR}/ext/debian/puppet.init /etc/init.d/puppet
  chmod 755 /etc/init.d/puppet
fi

# Copy in init script config if none exists already (FIXME: support OS's other than Debian)
if [ ! -e /etc/default/puppet ] ; then
  cp ${PUPPET_GEM_DIR}/ext/debian/puppet.default /etc/default/puppet
  chmod 644 /etc/default/puppet
fi

# Copy in auth config if none exists already
if [ ! -e ${CONFIG_DIR}/auth.conf ] ; then
  cp ${PUPPET_GEM_DIR}/conf/auth.conf ${CONFIG_DIR}/auth.conf
  chmod 644 ${CONFIG_DIR}/auth.conf
fi
echo "Thank you for installing puppet!"

exit 0
