#!/bin/bash
#
# Perform necessary puppet removal steps after package is uninstalled.
#

PROGNAME=$(basename $0)
DEST_DIR="/opt/puppet"
CONFIG_DIR="/etc/puppet"
VAR_DIR="/var/lib/puppet"
LOG_DIR="/var/log/puppet"
PREFIX="/usr"

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if [ $1 -eq "purge" ]; then
  #Purge all the things
  #Remove puppet config files
  rm -rf $CONFIG_DIR
  rm -f /etc/default/puppet
  #Remove the var directoris
  rm -rf $VAR_DIR
  #Remove log files
  rm -rf $LOG_DIR
elif [ $1 -eq "remove" ] || [ $1 -eq "upgrade" ] || [ $1 -eq "failed-upgrade" ] || [ $1 -eq "abort-install" ] || [ $1 -eq "abort-upgrade" ] || [ $1 -eq "disappear" ]; then
  # Remove link for binaries
  rm -f $PREFIX/bin/puppet
  rm -f $PREFIX/bin/facter
  # Remove init script
  rm -f /etc/init.d/puppetmaster
  # Remove installed directory
  rm -rf $DEST_DIR
else
  # What did you break?
  error_exit "postrm called with unknown argument: $1"

fi

echo "puppet has been uninstalled!"

exit 0
